services:
    db:
        container_name: db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: memo
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - prisma-network
    app:
        container_name: app
        build:
            context: .
        image: nextjs-memo
        environment:
            NEXT_PUBLIC_API_URL: http://localhost:3000
            DATABASE_URL: 'postgresql://postgres:password@db:5432/memo?schema=public'
            NEXTAUTH_SECRET: test
        ports:
            - '3000:3000'
        depends_on:
            - db
        networks:
            - prisma-network
networks:
    prisma-network:
        driver: bridge

volumes:
    postgres_data:
